server:
  port: 8081
spring:
  kafka:
    producer:
      bootstrap-servers: 120.78.195.231:9092
    consumer:
      bootstrap-servers: 120.78.195.231:9092
      group-id: test
  data:
    hbase:
      quorum: 120.78.195.231
      maxsize: 50000


